// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Contexts;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.Model.UserScore", b =>
                {
                    b.Property<string>("uid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.Property<DateTime>("time_stamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("uid");

                    b.ToTable("user_score");
                });
#pragma warning restore 612, 618
        }
    }
}
